name: "clang-format Check"
description: "Use clang-format to see if your C/C++ code is formatted according to project guidelines."

branding:
  icon: "check-circle"
  color: "blue"

inputs:
  clang-format-version:
    description: 'The version of clang-format that you want to use.'
    required: false
    default: '10'
  check-path:
    description: 'The path to the directory you want to check for correct C/C++formatting. Default is the full repository.'
    required: false
    default: '.'
  ignore-paths:
    description: 'List of paths to omit during the format check. Default is none.'
    required: false
    default: ''

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    CLANG_FORMAT_VERSION: ${{ inputs.clang-format-version }}
    CHECK_PATH: ${{ inputs.check-path }}
    BLACKLIST: ${{ inputs.ignore-path }}
